'use strict';
const $=id=>document.getElementById(id);
const idle=$('idle'), restart=$('restart'), scene=$('scene'), poster=$('poster');

const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let motion=!reduced.matches, busy=false, sound=false, recoveryTimer;
const stationAudio=new StationAudio();
let skyOpen=false, racksOpen=false;
const practicalFlicker=new PracticalFlicker(scene,()=>motion&&!busy&&!skyOpen&&!racksOpen&&!document.hidden);
let returnFocus=null, history=[], historyIndex=0, currentPhase='online';
const phases={online:['Still online','Quietly keeping things running.'],flicker:['Power unstable','The station is losing power.'],offline:['Running on stubbornness','The generator is trying again.'],rack:['Racks coming back','One machine at a time.'],interior:['Lights returning','Almost back on call.'],sign:['Remote support returns','There it is.']};
function setPoster(src){poster.src=src;const source=poster.parentElement.querySelector('source');if(source)source.srcset=src;}
function announce(text){$('announcement').textContent=text;}
function phase(key){if(currentPhase===key)return;currentPhase=key;const [title,detail]=phases[key];$('stateTitle').textContent=title;$('stateDetail').textContent=detail;$('stateLamp').style.background=key==='offline'?'#d99c78':key==='online'?'#a9cda5':'#eab577';announce(title+'. '+detail);}
function updateMotion(){practicalFlicker.sync(); $('motionButton').textContent=motion?'Motion on':'Motion off';$('motionButton').setAttribute('aria-pressed',String(motion));scene.classList.toggle('still',!motion);if(motion&&!document.hidden&&!busy&&!skyOpen&&!racksOpen){idle.play().catch(()=>{announce('Animation could not play. The still scene is ready to explore.');});}else idle.pause();}
function finish(){clearTimeout(recoveryTimer);restart.pause();restart.hidden=true;idle.hidden=false;busy=false;setPoster('assets/station.webp');document.querySelectorAll('[data-restart]').forEach(b=>b.disabled=false);phase('online');updateMotion();}
function startRestart(){if(busy)return;busy=true;practicalFlicker.sync();document.querySelectorAll('[data-restart]').forEach(b=>b.disabled=true);if(!motion){setPoster('assets/outage.webp');phase('offline');recoveryTimer=setTimeout(finish,1800);return;}
idle.pause();restart.hidden=false;idle.hidden=true;restart.currentTime=2;phase('flicker');restart.play().catch(()=>{scene.classList.add('still');setPoster('assets/outage.webp');phase('offline');recoveryTimer=setTimeout(finish,1800);});}
restart.addEventListener('timeupdate',()=>{if(!busy)return;const t=restart.currentTime;phase(t<3?'flicker':t<5?'offline':t<6.8?'rack':t<8?'interior':t<10?'sign':'online');});
restart.addEventListener('ended',finish);restart.addEventListener('error',()=>{if(busy){finish();announce('The animation could not load. The station is still available.');}});
document.querySelectorAll('[data-restart]').forEach(b=>b.addEventListener('click',startRestart));
$('motionButton').addEventListener('click',()=>{motion=!motion;if(busy)finish();updateMotion();});
reduced.addEventListener('change',e=>{motion=!e.matches;if(busy)finish();updateMotion();});
document.addEventListener('visibilitychange',()=>{practicalFlicker.sync();if(document.hidden){idle.pause();restart.pause();stationAudio.suspend();}else{if(sound)stationAudio.resume();if(busy&&motion&&!skyOpen)restart.play().catch(finish);else updateMotion();}});
$('soundButton').addEventListener('click',async()=>{try{await stationAudio.enable(!sound);sound=!sound;syncSoundFrames();$('soundButton').textContent=sound?'Sound on':'Sound off';$('soundButton').setAttribute('aria-pressed',String(sound));}catch{announce('This browser could not start audio. The scene works without it.');}});
let audioFrame=0;
function soundFrame(){audioFrame=0;if(!document.hidden&&sound){stationAudio.update(busy&&motion,restart.currentTime);audioFrame=requestAnimationFrame(soundFrame);}}
function syncSoundFrames(){if(sound&&!document.hidden){if(!audioFrame)audioFrame=requestAnimationFrame(soundFrame);}else{cancelAnimationFrame(audioFrame);audioFrame=0;}}
document.addEventListener('visibilitychange',syncSoundFrames);
document.querySelectorAll('[data-sky]').forEach(button=>button.addEventListener('click',()=>{if(window.DesertSky)DesertSky.open({returnFocus:button});else announce('The sky could not load. Reload the page to try again.');}));
document.addEventListener('desertsky:open',()=>{skyOpen=true;practicalFlicker.sync();stationAudio.setSky(true);idle.pause();restart.pause();});
document.addEventListener('desertsky:close',()=>{skyOpen=false;practicalFlicker.sync();stationAudio.setSky(false);if(busy&&motion&&!document.hidden)restart.play().catch(finish);else updateMotion();});
document.addEventListener('stationracks:open',()=>{racksOpen=true;practicalFlicker.sync();});
document.addEventListener('stationracks:close',()=>{racksOpen=false;practicalFlicker.sync();});
function openDialog(dialog){returnFocus=document.activeElement;dialog.showModal();}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>returnFocus?.focus());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
function paragraph(parent,text){const p=document.createElement('p');p.textContent=text;parent.append(p);return p;}
function info(kind){const area=$('infoContent');area.replaceChildren();$('infoTitle').textContent='Field notes';{const fullHeading=document.createElement('h3');fullHeading.textContent='Full scene';area.append(fullHeading);const fullImage=new Image();fullImage.src='assets/station.webp';fullImage.alt='Full uncropped station artwork, including the Remote Support: Still Online sign and distant palms.';fullImage.width=1920;fullImage.height=1080;area.append(fullImage);paragraph(area,'Civilization may have packed up. Somebody is still on call.');paragraph(area,'Still Online is an original Blender diorama by xD00g: a battered desert service station converted into a makeshift data center. This small browser version lets you poke around without leaving sand in the keyboard.');paragraph(area,'Try the terminal, inspect the racks, or restart the generator. Sound is optional. Turn motion off for a quiet still-image experience.');const small=document.createElement('small');small.textContent='Rendered in Blender. Original modeled scene with generated texture images. No account or actual network commands. Google Analytics and private Doogster Stats measure visits and feature use; terminal commands and cable details are not sent. Analytics is disabled when your browser sends Do Not Track or Global Privacy Control.';area.append(small);}openDialog($('infoDialog'));}
$('aboutButton').addEventListener('click',()=>info('about'));
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.open==='terminal'){openDialog($('terminalDialog'));$('command').focus();}else if(window.StationRacks)StationRacks.open({returnFocus:b});}));
const responses={help:'Available commands:\nhelp     this small map\nstatus   how the station is doing\nls       look around\nabout    the story\nwhoami   who is on call\nreboot   restart the generator\nlinks    roads back home\nclear    wipe the console',ls:'workbench/   server-room/   spare-parts/\nDO_NOT_UNPLUG.txt   last-good-backup.tar',about:'An abandoned roadside station. A salvaged rack.\nSomeone decided this was worth keeping online.\n\nAn original interactive scene by xD00g.',whoami:'The person who noticed the lights were still on.',cat:'DO NOT UNPLUG.\nYes, that means this one too.',ping:'A fictional outpost, not a real network shell.\nThe desert declines to return your packets.'};
function output(text,cls){const p=paragraph($('terminalOutput'),text);if(cls)p.className=cls;while($('terminalOutput').children.length>60)$('terminalOutput').firstElementChild.remove();$('terminalOutput').scrollTop=$('terminalOutput').scrollHeight;}
function command(value){const input=value.trim();if(!input)return;history.push(input);history=history.slice(-50);historyIndex=history.length;output('station:~ $ '+input,'entered');const key=input.toLowerCase();if(key==='clear')$('terminalOutput').replaceChildren();else if(key==='status')output('SCENE SIMULATION\n'+phases[currentPhase].join('\n')+'\nRemote support: still a very long drive.'+(window.StationRacks?'\n\n'+StationRacks.getState().map(d=>d.name+'  '+(!d.powered?'OFF':d.booting?'BOOTING':d.linked?'LINK / PORT '+d.port:'NO LINK')).join('\n'):''));else if(key==='reboot'){output(busy?'Restart already in progress. Give it a moment.':'Starting generator recovery. Watch the station.');$('terminalDialog').close();startRestart();}else if(key==='links'){output('Two roads out of here:');const p=document.createElement('p');for(const [label,url] of [['xD00g','https://www.doogster.com/'],['Nebulys','https://www.nebulys.net/']]){const a=document.createElement('a');a.href=url;a.textContent=label;a.target='_blank';a.rel='noopener noreferrer';p.append(a,document.createTextNode('   '));}$('terminalOutput').append(p);}else if(key.startsWith('cat '))output(responses.cat);else output(responses[key]||'Command not found. Try help.');$('command').value='';}
$('terminalForm').addEventListener('submit',e=>{e.preventDefault();command($('command').value);});
document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{command(b.dataset.command);$('command').focus();}));
$('command').addEventListener('keydown',e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();historyIndex=Math.max(0,Math.min(history.length,historyIndex+(e.key==='ArrowUp'?-1:1)));$('command').value=history[historyIndex]||'';}});
updateMotion();
